services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pharmawatch
      POSTGRES_PASSWORD: pharmawatch
      POSTGRES_DB: pharmawatch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
